name: flutter_email_sender_example
description: Demonstrates how to use the flutter_email_sender plugin.

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+20
  path_provider: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_email_sender:
    path: ../


flutter:
  uses-material-design: true
